version: '3'

services:
  postgresql:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: dft_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - '15432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    networks:
      confnetwork:
        ipv4_address: 10.0.0.5

networks:
  confnetwork:
    external: true