version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker/data/es1/log:/var/log
      - ~/docker/data/es1/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 256M
    #     reservations:
    #       memory: 256M
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker/data/es2/log:/var/log
      - ~/docker/data/es2/data0:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 256M
    #     reservations:
    #       memory: 256M
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/docker/data/es3/log:/var/log
      - ~/docker/data/es3/data:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    # deploy:
    #   replicas: 1
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 256M
    #     reservations:
    #       memory: 256M
    #   restart_policy:
    #     condition: on-failure
    #     max_attempts: 3

