version: '3.7'
serviceso:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es1:9200/
    ports:
      - 5601:5601
    volumes:
      - ~/docker/data/kibana/log:/var/log
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
