version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 12345678
    volumes:
      - ./data:/var/lib/grafana
    networks:
      confnetwork:
        ipv4_address: 10.0.0.7

networks:
  confnetwork:
    external: true