version: '3'

services:
  confluence-server:
    image: atlassian/confluence:7.13.0
    container_name: confluence
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - './data:/var/atlassian/application-data/confluence'
    environment:
      ATL_JDBC_URL: jdbc:postgresql://10.0.0.5:5432/confdb
      ATL_JDBC_USER: confdb
      ATL_JDBC_PASSWORD: confdb
      ATL_DB_TYPE: postgresql
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_SCHEMA_NAME: public
    networks:
      confnetwork:
        ipv4_address: 10.0.0.6

networks:
  confnetwork:
    external: true