version: "3"
services: 
 db:
  restart: always
  container_name: mysql
  image: mysql:8.1
  environment:
   TZ: Asia/Shanghai
   MYSQL_ROOT_PASSWORD: 123456
  ports:
   - 3306:3306
  volumes: 
   - ./data:/var/lib/mysql
